### ISSUE TITLE
Clients don't disconnect from server if they crash/force exit

### ISSUE THREAD

**Issue by jnterry** [CosyClub/ProjectTempo#100]
To reproduce, close a client by pressing Ctrl-C in terminal, re-join game with new client, the entity for the closed client will still be in the game.

Maybe implement some sort of heartbeat that says if server hasn't heard from client in X seconds assume it has crashed/disconnected

**Comment by AnthonyWharton** [comment]
Thanks, duly noted - Will work on something for this at some point, however not a top priority at the moment I don't think!

**Comment by qqii** [comment]
Would this cause problems when demoing? To prevent having to restart the client and server?

**Comment by grant-m-s** [comment]
#117 nearly complete
