### ISSUE TITLE
More Complex Button Mechanics

### ISSUE THREAD

**Issue by jnterry** [CosyClub/ProjectTempo#121]
Tilo's feedback emphasises the importance of group mechanics, and to achieve that we may want to support more interesting button mechanics.

Eg a big multi-tile dance pad area where 1 or more players must move around following a pattern (with tiles lighting up in advance to show where to go next). If we add parties we may want to prevent any players from other parties entering the dance area so they cant mess it up for another party.

Also, groups of buttons that must be stepped on in sequence, eg, that flash "on" and then must be stood on, required multiple players to coordinate when they will jump on.

Or any other ideas for fun multi-player interactions

**Comment by grant-m-s** [comment]
New Button Mechanics #131
