### ISSUE TITLE
Data Capturing Client

### ISSUE THREAD

**Issue by jnterry** [CosyClub/ProjectTempo#124]
Me and @qqii had a discussion about the demo day after easter, it would be nice to be able to have the client capture the inputs so we can "playback" a session at a later time, examine playstyle etc. Having a dummy client that replayed a captured input stream would also be good for stress testing and may get us some marks for the "A well-organised development and testing cycle" category.

------------------

At the very least we should probably record stats about how successful players are at hitting within the beat window (similar to that initial tool for measuring it) so we have some data to put in report to show we have tested the game and ensured it is not too easy, but also not a frustrating experience.

**Comment by qqii** [comment]
Completed for #157, but further work could be done to facilitate replays.
