### ISSUE TITLE
Dynamically change tile colour

### ISSUE THREAD

**Issue by Codrin-Popa** [CosyClub/ProjectTempo#128]
Idea 1: Change the tile color from red to other colors every so often.

Idea 2: Change the tile color depending on the combo:
red: 0 - 10
orange: 10-25
green: 25-50
blue: 50+

Idea 3: Change the tile color once an ability is triggered

**Comment by grant-m-s** [comment]
Hows this going?

**Comment by Codrin-Popa** [comment]
I made a few experiments and at the moment the floor is changing colour depending on the combo level.
x < 5, everything is grey
15 > x > 5 red,normal as we know it
30 > x > 15 orange
40 > x > 30 yellow

I can change it so it picks a random colour from a set of colours. This this could be used by the ambient lighting changes as well. I will give it a go later today.

**Comment by AnthonyWharton** [comment]
I know it's a bit similar to "a competitor", but I think everything being grey should be x == 0 only

**Comment by Codrin-Popa** [comment]
Colour for the tiles and for the ambient light is now randomly picked every beat. I randomly select an interpolation factor that is used to interpolate between red and purple in HSV space.
