### ISSUE TITLE
Make yAlignedBillboards face the camera.

### ISSUE THREAD

**Issue by AnthonyWharton** [CosyClub/ProjectTempo#158]
We still want them to be aligned to the up/down "y axis" (if it is even that because I'm not sure about this seemingly inconsistent coordinate system), but have them face towards the camera instead of straight "forwards". 

This should help a bit with perspective of billboards looking poor when towards the bottom corners of the camera.

**Comment by grant-m-s** [comment]
"Make yAlignedBillboards face the camera." talk about an oxymoron

**Comment by qqii** [comment]
I might play around with the camera first, I think that an isometric (or playing around with the camera options) might do the same thing.

**Comment by qqii** [comment]
Closed by #164 

Changes should be played with, especially camera FOV
