### ISSUE TITLE
colour_index causes crash on windows

### ISSUE THREAD

**Issue by AnthonyWharton** [CosyClub/ProjectTempo#168]
Steps to reproduce (on current `master` branch):

1) Build
2) Run server
3) Run client - this should be fine.
4) Close client
5) Run another client - crashes.

![image](https://user-images.githubusercontent.com/7091722/38906249-5d7f46f8-42ad-11e8-801f-e0672e58b652.png)

**Comment by AnthonyWharton** [comment]
On further testing, it appears to be a bit intermittent as to whether or not this happens. Perhaps some sort of a race condition? Going to bed now, will catch up in the morning.

**Comment by qqii** [comment]
This is a race condition, just define color_index = 0.
