### ISSUE TITLE
Implement Combo System

### ISSUE THREAD

**Issue by Codrin-Popa** [CosyClub/ProjectTempo#26]
Implement a component and a system for tracking combos.
This will be used for tracking player combos.

Every time a player does an action on the beat the beat counter increments. Failing to do so will reset the beat counter.

Combo levels will also be specified and they depend on the beat counter. Damage dealt by a player will be multiplied by this combo level.

**Comment by AnthonyWharton** [comment]
Just a thought:

Should the combo component have the logic as to whether or not something is valid for a combo, within the component it self. Then, the component can be used by the keyboard input system/AI movement system (if we wanted AI combos), making it a bit more portable and general as to whether or not something has a combo?
