### ISSUE TITLE
Client crashing when spawning 

### ISSUE THREAD

**Issue by Codrin-Popa** [CosyClub/ProjectTempo#28]
Client crashes if it spawns on top of another entity.
Posible fix:
Check with the server if we can spawn in a location.

**Comment by AnthonyWharton** [comment]
The server is what decides where you can spawn, This is just synced to the client. So that bug will likely be in the spawning code.

**Comment by Codrin-Popa** [comment]
How can I query the server if there is an entity on a tile?

**Comment by AnthonyWharton** [comment]
You don't need to. Assume the client and server are in sync. (They won't be the case yet in reality as AI is random movements done locally on whichever machine).

Random AI's will be removed once I get handshake sorted, and we work on proper core. With the proper core we will have these movements synced properly.
