### ISSUE TITLE
Implement HUD/Pop Up message/display thingy

### ISSUE THREAD

**Issue by AnthonyWharton** [CosyClub/ProjectTempo#56]
Something to display text prompts on the screen (w|c)ould be useful.

However I think something that pops above the player when we need to prompt them with something (e.g. a button that requires a certain level of combo, or a door that requires a key, or a key they need to press to pick up an item).

I imagine the pop up looks a bit like a black speech box, with a little glyph or icon in it to show the user what the hell is going on. Maybe slightly like the sims? I can't think of a good example. Probably nag Anthony to draw something.

**Comment by grant-m-s** [comment]
@AnthonyWharton "nag Anthony to draw something."

**Comment by qqii** [comment]
Some initial work has been completed, further specific details should be made in a new issue.
